### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zeeeeby** [GoogleFeud/ts-runtime-checks#37]
**Describe the bug**
Hello, i didn't understand, why this code does not generate validators for `body: { user: User }`. 
Can you please help?

**Playground link**
[link](https://googlefeud.github.io/ts-runtime-checks?code=PTAEEkDsBcFMCcCGBjaBLAbrUAHANogJ4Dm8A9gK6QAmAhKAOrxpyhqSiGXyjJnXZENUAGdY2FqGKxo6SMVDQkkETjR5Y1UGQ7QAFtg0AzaLQBQ0QjmwBVMTwC8oAN5nQ70JEQBbWAC5RJXZiABo3DzRqAMgKbwAjBDMAXwsrbAARACE7BFAnHJ4AMhdQPTQAkSD5UBSzIypUNB1QWBocMnZoAB5M-kI8lySQ0ABFCgR+p2ch0AAJWEQBeBEB6eGAJVgRCjxoAYwO6gA+AAojAJP4WABHAM3r8crhq5E7rfaVWGHYAA8lRACrg8oDifQCAEERPZulAjAgen0jkcwsCcIgkN5XqBIdCuvNFggRMjkgBKPJHUAABXI3jQYi6m22uyOJLMQI8V2gFHgHEQIkIkGQoEuNzeDy20GeWzeqh0YmGzhBYNAvWohGGaIxWMp6J8KySZIcR3C7nZwPcGj2AG1QWqALoDZAGZAAawRatOV2uADpbYRWeaPJbQFbNXqHU4nbBXXiFksiSKfQYCcsA4HQMGXjs9k5EAB3RCSIyJqUiBVKtUa3WYmppwN8FRkDTevBkYgipnQOvmzncjgvE01ZJmMzB6Q5lptDowLqKij2AIFGqnPkCoUl0Avb5-JCG41mjMyNhaJy-f6+vre+cIb2RUkjoA)

![image](https://github.com/GoogleFeud/ts-runtime-checks/assets/44382546/3926c839-2c0d-4d2b-ac8c-fb3f4cfd4418)

**Comment by GoogleFeud** [comment]
Hi, the `Assert` markers don't generate any code because they're inside of a function type definition, they should be removed as they don't do anything.

Type parameters by themselves don't generate any validation code, you need to wrap the types you pass to the `check` function with `Infer` - [playground](https://googlefeud.github.io/ts-runtime-checks?code=PTAEEkDsBcFMCcCGBjaBLAbrUAHANogJ4Dm8A9gK6QAmAhKAOrxpyhqSiGXyjJnXZENUAGdY2FqGKxo6SMVDQkkETjR5Y1UGQ7QAFtg0AzaLQBQ0QjmwBVMTwC8oAN5nQ70JEQBbWAC5RJXZiABo3DzRqAMgKbwAjBDMAXwsrbAARACE7BFAnHJ4AMhdQPTQAkSD5UBSzIypUNB1QWBocMnZoAB5M-kI8lySQ0ABFCgR+p2ch0AAJWEQBeBEB6eGAJVgRCjxoAYwO6gA+AAojAJP4WABHAM3r8crhq5E7rfaVWGHYAA8lRACrg8oDifQCvWohDCwJwiCQ3lecwWSxEYSSAEo8kdQAAFcjeNBiLqbba7I7osxAjxXaAUeAcRAiQiQZCgS43N4PLbQZ5bN6qHRiTEOI7hdxU4HuDR7ADaoMhw3lhAAaog8JFEOgdABReDkZYAXQGyAMyAA1l0oEYED0+kdTldrgA6JUUyURIxspWq9XUTVNSC6-UiJ0aeT6TH6cgAd08sFjQbI8BO3rVGq1gb1SZDACsOpATgAiYaF9GYsWS6WgGWw+Go3Bwnw+9MBxOG42mi1Wm3zRYIET29nOgx95Zu91sT0nWtNtN+jNtkNh4gRxR6GNxhNZ5Mz7zN+et7e5-NFktlivAqsvHZ7JyIaOISRGIe8+vOEF9Ya7lYYi8ePgqGQGihmQxDsqS0Dju6NJ0hwLwViktRVtIt4tG0+bdO+FD2AEBTDGa7BRKAhbYQghY1KcjLMqyL6gC83x-EgwqihKoBVpEAy-P8Lp9E6pHwE6kTJBSQA)

It's also a good idea to create a discriminated union of the objects that could be `User` - otherwise passing different objects breaks the validation code:

```ts
enum PossibleEndpointBodies {
    User,
    DBUser
}

let get = endpoint<{ user: User, kind: PossibleEndpointBodies.User }>(async (req, res, extra) =>
{
    let id = extra.body.user.id
})

let get1 = endpoint<{ user: DBUser, kind: PossibleEndpointBodies.DBUser }>(async (req, res, extra) =>
{
    let id = extra.body.user.id
})
```

**Comment by zeeeeby** [comment]
That's awesome! Thanks for explaining!
